import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import { Inter } from "next/font/google";
import { Notification } from "@/components";
import ThemeProvider from "@/contexts/Theme";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <main className="min-h-[100vh] flex flex-col justify-between bg-no-repeat bg-cover bg-center bg-[var(--layout-bg)] !bg-[#FCFEF9]">
            <Header />
            <div className="flex-1">{children}</div>

            {/* <Footer /> */}

            <Notification />
            <ToastContainer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
